build: false

os: Visual Studio 2015

platform:
  - x64
  - x86

environment:
  matrix:
    - MINICONDA: C:\xtensor-conda

init:
  - "ECHO %MINICONDA%"
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\xtensor-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "set PYTHONHOME=%MINICONDA%"

  ## Install xtensor-python
  #- conda install xtensor-python -c conda-forge

  # Install cookiecutter and pytest
  - conda install numpy
  - conda install pytest cookiecutter -c conda-forge
  
  # Run cookiecutter in build directory
  - mkdir build
  - cd build
  - cookiecutter %APPVEYOR_BUILD_FOLDER% --no-input
       # Defaults to
       # "author_name": "",
       # "author_email": "",
       # "github_project_name": "xtensor-example-extension",
       # "github_organization_name": "QuantStack",
       # "python_package_name": "xtensor_example_extension",
       # "cpp_namespace": "ext",
       # "project_short_description": "An example xtensor extension"
  #- pip install .\\my-new-project

build_script:
  - py.test -s
